const A='../../../public/';
document.getElementById('app').innerHTML=`<main class="film">
  <nav class="nav"><div class="mark">PHOLIO</div><a href="index.html">Studies</a></nav>
  <section class="hero"><div class="hero-word">PHOLIO</div><img class="hero-model" src="${A}images/model2-nobg.png" alt="Model portrait"><div class="hero-verb">Present</div></section>
  <section class="scene media"><h2 class="scene-title">The book</h2><div class="media-stage"><img class="media-photo a" src="${A}generated/comp-card/source/mara-voss-red-hero.jpg" alt="Editorial portrait"><img class="media-photo b" src="${A}generated/comp-card/source/mara-voss-crossed-arm.jpg" alt="Portfolio frame"><img class="media-photo c" src="${A}generated/comp-card/source/mara-voss-profile.jpg" alt="Profile frame"><div class="scan"></div><div class="taxonomy"><span class="active">Digitals</span><span>Book</span><span>Tests</span><span>Campaigns</span><span>Tearsheets</span><span>Motion</span></div></div></section>
  <section class="scene profile"><h2 class="scene-title small">Profile</h2><article class="profile-sheet"><img src="${A}generated/comp-card/source/mara-voss-profile.jpg" alt="Talent profile portrait"><div class="profile-copy"><div><div class="micro">Mara Voss</div><div class="profile-name">Identity,<br>ready to cast.</div></div><div class="facts"><div class="fact"><span>Height</span><strong>180 cm</strong></div><div class="fact"><span>Playing age</span><strong>21-29</strong></div><div class="fact"><span>Base</span><strong>New York</strong></div><div class="fact"><span>Experience</span><strong>Professional</strong></div><div class="fact"><span>Availability</span><strong>Freelance</strong></div><div class="fact"><span>Travel</span><strong>Open</strong></div></div><div class="profile-foot"><span>Credits</span><span>Training</span><span>Skills</span><span>Preferences</span></div></div></article></section>
  <section class="scene website"><h2 class="scene-title small">Your site</h2><div class="web-canvas"><div class="web-cover"><img src="${A}generated/comp-card/source/mara-voss-red-hero.jpg" alt="Public portfolio cover"><div class="url">maravoss.pholio.studio</div></div><div class="web-grid"><img src="${A}generated/comp-card/source/mara-voss-crossed-arm.jpg" alt="Portfolio image"><img src="${A}generated/comp-card/source/mara-voss-profile.jpg" alt="Portfolio image"><div class="web-analytics"><strong>Visits</strong><span>Views, page reads, outbound clicks</span></div></div></div></section>
  <section class="scene comp"><h2 class="scene-title small">Comp card</h2><div class="comp-wrap"><img class="comp-source cs1" src="${A}generated/comp-card/source/mara-voss-crossed-arm.jpg" alt="Selected book frame"><img class="comp-source cs2" src="${A}generated/comp-card/source/mara-voss-profile.jpg" alt="Selected book frame"><div class="comp-card"><img class="front" src="${A}generated/comp-card/elara-keats-front.png" alt="Comp card front"><img class="back" src="${A}generated/comp-card/elara-keats-back.png" alt="Comp card back"></div><div class="editions">FRONT / BACK / EDITIONS / WALLET</div></div></section>
  <section class="scene submit"><h2 class="scene-title small">Submit</h2><article class="dossier"><aside class="agency-rail"><div><div class="micro">Representation</div><div class="agency-name">Lumen<br>Models</div></div><span>Board selected: Editorial</span></aside><div class="package"><div class="package-piece"><img src="${A}generated/comp-card/source/mara-voss-profile.jpg" alt="Submission digitals"><span>Digitals</span></div><div class="package-piece"><img src="${A}generated/comp-card/source/mara-voss-red-hero.jpg" alt="Submission book"><span>Book</span></div><div class="package-piece cardpiece"><img src="${A}generated/comp-card/elara-keats-front.png" alt="Submission comp card"><span>Card</span></div><div class="package-piece"><img src="${A}generated/comp-card/source/mara-voss-crossed-arm.jpg" alt="Submission profile"><span>Stats</span></div><div class="sendline"><span>Digitals, stats, book, comp card, message</span><strong>Package ready</strong></div></div></article></section>
  <section class="scene connect"><h2 class="scene-title small">In motion</h2><div class="connect-space"><div class="thread">“We would like to meet you for our editorial board.”<span>Messages / writing assist</span></div><article class="interview"><div class="micro">Interview</div><h3>Thursday<br>10:30 AM</h3><div class="interview-meta"><div>Format<strong>Video call</strong></div><div>Status<strong>Awaiting response</strong></div></div></article></div></section>
  <section class="scene intel"><h2 class="scene-title small">Intel</h2><div class="intel-field"><div class="signal s1">Search signal</div><div class="signal s2">Agency lens</div><div class="signal s3">Book ranked</div><div class="signal s4">Trajectory</div><div class="signal s5">Market board / Pipeline / Attention</div><div class="intel-center">Intel</div></div></section>
  <section class="end"><div class="end-word">PHOLIO</div></section><div class="chapter"></div><div class="grain"></div></main>`;

gsap.registerPlugin(ScrollTrigger);
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduce){
  const mode=document.documentElement.dataset.mode;
  const scenes=['media','profile','website','comp','submit','connect','intel'];
  const labels=['Book','Profile','Site','Card','Submit','Connect','Intel'];
  gsap.set('.chapter',{opacity:1});
  if(mode==='darkroom') darkroom(); else if(mode==='identity') identity(); else contact();
  function base(){return gsap.timeline({scrollTrigger:{trigger:document.body,start:'top top',end:'bottom bottom',scrub:1.15}}).to('.hero-model',{scale:1.28,y:'12vh',opacity:.08,duration:1.1,ease:'power3.inOut'},0).to('.hero-word',{scale:1.18,opacity:.06,duration:1.1},0).to('.hero-verb',{opacity:0,y:-18,duration:.4},.2)}
  function chapter(tl,name,at){tl.call(()=>document.querySelector('.chapter').textContent=name,null,at)}
  function darkroom(){const tl=base();let at=.55;scenes.forEach((s,i)=>{chapter(tl,labels[i],at);tl.to('.'+s,{opacity:1,duration:.55},at);if(s==='media'){tl.from('.media-photo',{clipPath:'inset(50% 0)',scale:.82,stagger:.08,duration:1.0,ease:'power3.inOut'},at).to('.scan',{y:'56vh',duration:1.2,ease:'power1.inOut'},at+.05)}if(s==='profile')tl.from('.profile-sheet',{scale:.72,rotationX:8,y:'10vh',duration:.9,ease:'power3.out'},at);if(s==='website')tl.from('.web-canvas',{scale:.72,x:'15vw',duration:.9,ease:'power3.out'},at);if(s==='comp')tl.from('.comp-card',{scale:.12,rotationY:-35,duration:1.0,ease:'power4.out'},at).to('.comp-card',{rotationY:180,duration:.85,ease:'power3.inOut'},at+.65);if(s==='submit')tl.from('.dossier',{scale:.68,rotationY:8,duration:.9,ease:'power3.out'},at);if(s==='connect')tl.from('.thread',{x:'-18vw',opacity:0,duration:.8},at).from('.interview',{x:'18vw',opacity:0,duration:.8},at);if(s==='intel')tl.from('.intel-center',{scale:.15,duration:.9,ease:'power4.out'},at).from('.signal',{opacity:0,scale:.8,stagger:.05,duration:.65},at+.2);if(i<scenes.length-1)tl.to('.'+s,{opacity:0,scale:1.12,duration:.58,ease:'power2.in'},at+1.25);at+=1.18});tl.to('.intel',{opacity:0,scale:1.25,duration:.8},at+.45).to('.end',{opacity:1,duration:.8},at+.6)}
  function identity(){const tl=base();let at=.6;scenes.forEach((s,i)=>{chapter(tl,labels[i],at);tl.to('.'+s,{opacity:1,duration:.45},at).fromTo('.'+s,{z:-600,rotationY:i%2?8:-8},{z:0,rotationY:0,duration:1.0,ease:'power3.out'},at);if(s==='comp')tl.to('.comp-card',{rotationY:180,duration:.9,ease:'power3.inOut'},at+.55);tl.to('.hero-model',{x:i%2?'-28vw':'28vw',scale:.62,opacity:.18,duration:.85,ease:'power2.inOut'},at);if(i<scenes.length-1)tl.to('.'+s,{x:i%2?'22vw':'-22vw',z:350,opacity:0,duration:.65,ease:'power2.in'},at+1.15);at+=1.12});tl.to('.intel',{opacity:0,scale:.25,rotationZ:6,duration:.8},at+.4).to('.hero-model',{x:0,opacity:0,duration:.5},at+.4).to('.end',{opacity:1,duration:.85},at+.65)}
  function contact(){const tl=base();let at=.55;gsap.set('.scene',{opacity:.13});scenes.forEach((s,i)=>gsap.set('.'+s,{x:(i%3-1)*92+'vw',y:(Math.floor(i/3)-1)*82+'vh',scale:.72}));tl.to('.hero',{opacity:0,duration:.55},.55);scenes.forEach((s,i)=>{chapter(tl,labels[i],at);tl.to('.'+s,{x:0,y:0,scale:1,opacity:1,duration:.9,ease:'power3.inOut'},at);if(s==='comp')tl.to('.comp-card',{rotationY:180,duration:.75},at+.45);tl.to('.'+s,{x:(i%2?'-85vw':'85vw'),y:(i%3-1)*24+'vh',scale:.58,opacity:.14,duration:.8,ease:'power2.inOut'},at+1.05);at+=1.0});tl.to('.scene',{opacity:0,duration:.65},at+.3).to('.end',{opacity:1,duration:.8},at+.55)}
}
