"use client";

import {
  LegalDocumentLayout,
  type LegalSection,
} from "@/components/LegalDocumentLayout";
import {
  COMPANY_NAME,
  COMPANY_ADDRESS,
  LAST_UPDATED,
  EFFECTIVE_DATE,
  LEGAL_EMAIL,
  PRIVACY_EMAIL,
} from "@/lib/legal-constants";

const sections: LegalSection[] = [
  {
    title: "Purpose of This Notice",
    content: [
      `${COMPANY_NAME} ("Pholio," "we," "our," or "us") uses artificial intelligence (AI) and machine learning technologies as part of optional features on the Pholio platform (www.pholio.studio and app.pholio.studio, collectively the "Platform").`,
      `This AI Notice explains what AI systems we use, how they work, what data they process, the limitations and risks of AI-generated outputs, and your rights with respect to AI features. We are committed to transparency about our use of AI so you can make informed decisions about whether and how to use these features.`,
      `This Notice supplements our Privacy Policy (www.pholio.studio/privacy) and Terms of Service (www.pholio.studio/terms). In the event of any conflict, the Privacy Policy governs with respect to data handling.`,
    ],
  },
  {
    title: "AI Systems We Use",
    content: [
      `2a. Groq — Photo Quality Analysis\nWe use the Groq, Inc. inference API to process portfolio photographs uploaded by Talent users who have opted into AI-assisted features. Groq's large language model infrastructure analyzes image composition, lighting quality, technical sharpness, and overall presentation suitability to generate curation recommendations and quality scores. Images submitted to Groq are processed transiently for inference purposes and are governed by Groq's data processing terms. We do not permit Groq to use submitted images for model training.`,
      `2b. OpenAI — Semantic Embeddings\nWe use the OpenAI API to generate vector embeddings of talent profile text data (such as biography, portfolio categories, and professional descriptors). These embeddings are numerical representations stored in our vector database (pgvector) and are used to power semantic search and agency-talent match scoring features. Profile text submitted to OpenAI is processed under our data processing agreement with OpenAI and is not used for training OpenAI's general models.`,
      `2c. Match Scoring\nWe compute agency-talent match scores using a combination of OpenAI-generated embeddings and rule-based signals (e.g., geographic proximity, category alignment, profile completeness). Match scores are displayed to Agency users as a ranking aid when reviewing talent applications and search results.`,
      `2d. No Other AI Systems\nAs of the Effective Date of this Notice, we do not use any other AI systems for decisions that affect users on the Platform. If we introduce additional AI capabilities in the future, we will update this Notice and notify users in accordance with our standard notification procedures.`,
    ],
  },
  {
    title: "Opt-In Consent Required",
    content: [
      `AI-assisted photo analysis is an opt-in feature only. We will not transmit your portfolio images to any AI system without your explicit, affirmative consent.`,
      `You provide consent by enabling the AI analysis feature in your account settings. The consent screen clearly identifies that images will be sent to Groq for processing and describes what the analysis produces.`,
      `You may withdraw your consent at any time by disabling AI features in your account settings. Withdrawal of consent will stop any future AI processing of your images. It does not retroactively delete prior analysis results already stored in your account, but you may request deletion of those results by contacting ${PRIVACY_EMAIL}.`,
      `OpenAI embedding generation for profile text is a backend feature that applies to all Talent accounts as part of the Platform's core search and matching infrastructure. You may opt out of match scoring features by contacting ${PRIVACY_EMAIL}; note that opting out may affect your discoverability to Agency users.`,
    ],
  },
  {
    title: "Advisory Nature of AI Outputs",
    content: [
      `ALL AI-generated outputs on the Pholio platform are advisory only. This includes:`,
      `— Photo quality scores and curation recommendations generated by Groq;`,
      `— Agency-talent match scores computed using OpenAI embeddings;`,
      `— Any ranking, sorting, or suggested ordering of talent profiles in agency search results.`,
      `AI outputs do not constitute professional opinions, editorial judgments, casting decisions, or any form of contractual representation. They are tools to assist users — not automated decision-makers.`,
      `Match scores and recommendations should be treated as one signal among many. Agency users are expected to apply their own professional judgment when evaluating talent. Talent users should not rely on AI scores as an authoritative assessment of their professional viability or suitability for any particular opportunity.`,
      `PHOLIO MAKES NO WARRANTY OR REPRESENTATION REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR SUITABILITY OF ANY AI-GENERATED OUTPUT. AI SYSTEMS CAN AND DO PRODUCE INACCURATE, OUTDATED, OR CONTEXTUALLY INAPPROPRIATE RESULTS.`,
    ],
  },
  {
    title: "Human Review Available",
    content: [
      `No AI output on the Pholio platform produces a legally binding or solely automated decision that determines your access to services, your account status, or any outcome with significant real-world consequences.`,
      `If you believe an AI-generated output — including a match score, a quality assessment, or a search ranking — is incorrect, misleading, or has unfairly affected your use of the Platform, you have the right to request a human review.`,
      `To request human review of an AI output, contact ${LEGAL_EMAIL} with a description of the output you are disputing and the basis for your concern. We will investigate within a reasonable time and respond substantively.`,
      `This human review right is in addition to any rights you may have under the GDPR's Article 22 (automated individual decision-making) or equivalent provisions under applicable data protection law.`,
    ],
  },
  {
    title: "Bias and Limitations",
    content: [
      `We acknowledge that AI systems — including those we use — can reflect and amplify biases present in their training data. We are committed to responsible AI use and disclose the following known limitations:`,
      `6a. Visual Bias in Photo Analysis\nAI photo quality models trained predominantly on certain aesthetic or demographic norms may produce biased quality assessments. For example, models may score images differently based on skin tone, hair type, or body type in ways that reflect underlying biases in training data rather than objective quality. We treat photo quality scores as approximate and encourage users not to treat low scores as definitive judgments.`,
      `6b. Embedding Bias in Match Scoring\nSemantic embeddings of profile text may reflect language and cultural biases present in the model's training corpus. Match scores should not be used as the sole basis for any representation or hiring decision.`,
      `6c. No Discriminatory Use\nPholio does not and will not use any AI feature to make decisions based on race, ethnicity, national origin, religion, disability, age, sex, gender identity, sexual orientation, or any other protected characteristic. Match scoring is based on professional profile data, portfolio content, and agency search parameters — not personal protected attributes.`,
      `6d. Evolving Technology\nAI capabilities and their limitations evolve rapidly. We commit to periodic review of our AI features and this Notice, and to updating our practices as better information, tools, and standards become available.`,
    ],
  },
  {
    title: "Minors and AI Processing",
    content: [
      `Pholio does not apply AI photo analysis to portfolio images of users identified as minors (under 18) without the explicit consent of the minor's parent or legal guardian.`,
      `If you are the parent or guardian of a minor with a Pholio account and you have questions or concerns about AI processing of that minor's images, please contact ${PRIVACY_EMAIL}.`,
      `Pholio does not use AI to infer age from photographs and does not use age inference as a basis for any platform decision. Age on the Platform is determined by the information provided at account registration, which is subject to our standard age verification policies.`,
    ],
  },
  {
    title: "Data Handling for AI Features",
    content: [
      `Images sent to Groq for photo analysis are transmitted over encrypted connections and processed solely for the purpose of generating quality assessment outputs. We have a data processing agreement with Groq that prohibits use of submitted data for any purpose beyond fulfilling the API request.`,
      `Profile text sent to OpenAI for embedding generation is similarly covered by our data processing agreement with OpenAI. We have configured our OpenAI API use to disable training data opt-in.`,
      `Vector embeddings (numerical representations of profile text) are stored in our pgvector database as part of your account data. You may request deletion of your embeddings by contacting ${PRIVACY_EMAIL}; this will affect match scoring features.`,
      `For full details on how AI-related data is handled, retained, and your rights regarding that data, please review our Privacy Policy.`,
    ],
  },
  {
    title: "Contact and Questions",
    content: [
      `If you have questions about our use of AI, wish to exercise rights related to AI processing, or have concerns about the accuracy or fairness of any AI output, please contact:`,
      `Email: ${LEGAL_EMAIL}`,
      `Mailing address: ${COMPANY_ADDRESS}`,
      `We aim to respond to all substantive AI-related inquiries within five (5) business days.`,
    ],
  },
];

export function AiNoticeContent() {
  return (
    <LegalDocumentLayout
      title="AI Notice"
      subtitle="Pholio uses AI for optional photo analysis and match scoring features. This Notice explains what AI systems we use, how they work, the advisory nature of all AI outputs, and your rights — including opt-in consent and human review."
      lastUpdated={LAST_UPDATED}
      effectiveDate={EFFECTIVE_DATE}
      sections={sections}
      contactEmail={LEGAL_EMAIL}
      footerTitle="Questions About Our AI Features?"
      footerBody="For questions about our AI practices, opt-out requests, or to request human review of any AI-generated output, contact our legal team."
      companyName={COMPANY_NAME}
      companyAddress={COMPANY_ADDRESS}
    />
  );
}
