"""
Encode the green-screen hero film into the transparent WebP scrub sequence.

Unlike encode_cutouts.py (which trusted hand-delivered alpha), this keys a solid
chroma-green background itself. The source is ONE continuous film generated by
Seedance: Clip A (seated hero pose -> stands -> camera pull-back to full body)
chained frame-exact into Clip B (one 360 casting turn), concatenated with Clip
B's duplicate first frame dropped. Because it is a single continuous take, the
poster (frame 0) and the sequence share one identity/outfit/lighting -- no
crossfade or face-lock hack is needed downstream.

Pipeline: extract frames -> chroma-key (matte erosion + full despill + edge
decontamination, tuned in scratchpad) -> uniformly subsample to TARGET frames
(always keeping frame 0 as the seated poster) -> one union bbox across every
kept frame so they stay mutually registered while scrubbing -> crop, downscale
to MAX_H, encode WebP with alpha. Also writes rest.webp (the full-res keyed
poster) and the manifest.

Usage:  /opt/anaconda3/bin/python3.12 encode_greenscreen.py <film.mp4> [target]
"""

import json
import pathlib
import subprocess
import sys
import tempfile

import numpy as np
from PIL import Image
from scipy import ndimage

BBOX_PAD = 10
MAX_H = 1000
WEBP_QUALITY = 82
TARGET = 130          # scrubbable frame count (default)

# chroma-key knobs (validated in scratchpad/keytest2.png)
KEY_LO, KEY_HI = 22, 72
ERODE = 1
EDGE_DESAT = 0.9

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "public/hero-sequence"


def key_frame(rgb: np.ndarray):
    """Green-screen key -> (despilled RGB float, alpha float 0..1)."""
    a = rgb.astype(float)
    R, G, B = a[..., 0], a[..., 1], a[..., 2]
    mx = np.maximum(R, B)
    greenness = G - mx
    alpha = np.clip((KEY_HI - greenness) / (KEY_HI - KEY_LO), 0, 1)
    if ERODE > 0:
        alpha = np.minimum(alpha, ndimage.grey_erosion(alpha, size=(2 * ERODE + 1, 2 * ERODE + 1)))
    spill = np.maximum(0, G - mx)
    Gd = G - spill                         # full despill: clamp green to max(R,B)
    out = np.stack([R, Gd, B], -1)
    lum = 0.299 * out[..., 0] + 0.587 * out[..., 1] + 0.114 * out[..., 2]
    t = (np.clip(spill / 40.0, 0, 1) * EDGE_DESAT)[..., None]
    out = out * (1 - t) + np.stack([lum, lum, lum], -1) * t
    return out.clip(0, 255), alpha


def rgba_from(rgb: np.ndarray) -> Image.Image:
    out, alpha = key_frame(rgb)
    arr = np.dstack([out, alpha * 255]).astype(np.uint8)
    return Image.fromarray(arr, "RGBA")


def main() -> None:
    film = pathlib.Path(sys.argv[1])
    target = int(sys.argv[2]) if len(sys.argv) > 2 else TARGET
    if not film.exists():
        raise SystemExit(f"no film at {film}")

    with tempfile.TemporaryDirectory() as td:
        tmp = pathlib.Path(td)
        print(f"extracting frames from {film.name} ...", flush=True)
        subprocess.run(
            ["/opt/homebrew/bin/ffmpeg", "-y", "-v", "error", "-i", str(film),
             str(tmp / "f%04d.png")],
            check=True,
        )
        frames = sorted(tmp.glob("f*.png"))
        S = len(frames)
        if S == 0:
            raise SystemExit("ffmpeg produced no frames")

        # uniform subsample, always including frame 0 and the last frame
        idx = sorted({round(i * (S - 1) / (target - 1)) for i in range(target)})
        print(f"{S} source frames -> {len(idx)} kept (target {target})", flush=True)

        rgbas = [rgba_from(np.asarray(Image.open(frames[j]).convert("RGB"))) for j in idx]
        w, h = rgbas[0].size

        # union bbox across every kept frame's alpha
        union = np.zeros((h, w), dtype=bool)
        for im in rgbas:
            union |= np.asarray(im)[..., 3] > 12
        ys, xs = np.where(union)
        x0 = max(0, int(xs.min()) - BBOX_PAD)
        y0 = max(0, int(ys.min()) - BBOX_PAD)
        x1 = min(w, int(xs.max()) + 1 + BBOX_PAD)
        y1 = min(h, int(ys.max()) + 1 + BBOX_PAD)
        print(f"union bbox: x{x0}-{x1} y{y0}-{y1}  ({x1-x0}x{y1-y0} of {w}x{h})", flush=True)

        scale = min(1.0, MAX_H / (y1 - y0))
        out_w, out_h = round((x1 - x0) * scale), round((y1 - y0) * scale)

        OUT.mkdir(parents=True, exist_ok=True)
        for old in OUT.glob("[0-9]*.webp"):
            old.unlink()

        for i, im in enumerate(rgbas):
            crop = im.crop((x0, y0, x1, y1))
            if scale < 1.0:
                crop = crop.resize((out_w, out_h), Image.LANCZOS)
            crop.save(OUT / f"{i:03d}.webp", "WEBP", quality=WEBP_QUALITY, method=6)
        print(f"wrote {len(rgbas)} webp frames @ {out_w}x{out_h}", flush=True)

        # poster == frame 0, cropped to the SAME union bbox as the scrub so it
        # registers pixel-for-pixel with frame 000.webp (object-contain in the
        # hero). Kept at bbox resolution (not downscaled) for a crisp first paint.
        rgbas[0].crop((x0, y0, x1, y1)).save(OUT / "rest.webp", "WEBP", quality=92, method=6)

        (OUT / "manifest.json").write_text(json.dumps({
            "source": "greenscreen-film",
            "format": "webp",
            "quality": WEBP_QUALITY,
            "count": len(rgbas),
            "restIndex": 0,
            "bbox": {"x": int(x0), "y": int(y0), "w": out_w, "h": out_h},
            "sourceSize": {"w": int(w), "h": int(h)},
        }, indent=2))
        print(f"done -> {OUT} ({len(rgbas)} frames, poster rest.webp)", flush=True)


if __name__ == "__main__":
    main()
